### PR TITLE
Added slovak and czech translation

### PR DESCRIPTION
**Pull request by JFox-sk**

### CODE REVIEW

**Comment by JFox-sk** [comment]
Please, can you make next release with this commits?
Thak you :-)

**Comment by JFox-sk** [comment]
I can not find new release on release page https://github.com/FolioReader/FolioReader-Android/releases :-(

**Comment by mahavir155** [comment]
Hi, We'll add this in next release. We haven't scheduled next release yet.

**Comment by JFox-sk** [comment]
Please, can you make next release? I would like to using FolioReader with slovak and czech translations as Gradle dependency (lib), but in last release are not these translations :-(

**Comment by mahavir155** [comment]
@JFox-sk Sorry to keep you waiting. Actually, we are busy integrating r2-streamer-kotlin and improving highlight feature. But that release will take more time. @hrishikesh-kadam will push the build from master with your translations.

**Comment by hrishikesh-kadam** [comment]
@JFox-sk Translations now live in version 0.4.4

**Comment by JFox-sk** [comment]
Thank you very much :-)

**Pull request merged**
