### PR TITLE
Three type of Orientation of contents

### PR DESCRIPTION
**Pull request by shahabrauf18**
Hello there,

I was facing the issue with horizontal scroll of contents that was not completely scroll horizontally, so i decided to enhance the library with three type of scrolling Horizontal, Vertical and Horizontal with vertical contents.

Regards,
Muhammad SHahab

### CODE REVIEW

**Comment by mahavir155** [comment]
@shahabrauf18 Thanks for sending pull request. It looks like, you implemented horizontal scrolling in java instead of javascript.. Looks interesting :). When we tested here, scrolling was not that softly. So, probably we'll need to test more. We'll keep that in separate branch for now and we'll improve more on this stuff..

Thanks for taking initiative for horizontal scrolling. It has been pending since long time :).

Thank you,
Mahavir

**Comment by shahabrauf18** [comment]
I am working on it to make it more smooth and reliable, I will make a pull request again.

Thanks 
Muhammad shahab

**Comment by blennerSilva** [comment]
is there any forecast on when this issue will be resolve or this pullrequest will be incorporated to the project?

**Comment by mahavir155** [comment]
@hebertialmeida I had already reviewed and I don't think it is ready for merge..

**Comment by hebertialmeida** [comment]
@mahavir155 Alright!

**Comment by LeoDiasDev** [comment]
@shahabrauf18 Can u see about reply?

**Comment by shahabrauf18** [comment]
I think i made a pull request for previous version. Now it has been changed a lot. I will have to make compatible with new version. If you want to use this functionality with older version you can use my forked one repository. https://github.com/shahabrauf18/FolioReader-Android

**Pull request closed without merging**
