### PR TITLE
Fixed a conflict of attributes with support library 26.1.0

### PR DESCRIPTION
**Pull request by Semper-Viventem**
Fixed the conflict of attributes with the support library 26.1.0, also a problem was found in the example with an unreadable ePub-file.

### CODE REVIEW

**Comment by GautamChibde** [comment]
@Semper-Viventem why did you close the pull request?

**Comment by Semper-Viventem** [comment]
@GautamChibde This request failed validation

**Comment by GautamChibde** [comment]
@Semper-Viventem your changes look good and as for Travis just try and update the **build-tools** version and **android** version in the file [travis.yml](https://github.com/FolioReader/FolioReader-Android/blob/master/.travis.yml)  and just update the pull request :smiley:.

**Comment by Semper-Viventem** [comment]
@GautamChibde 
Thank you. Raised api to 27, there were new build problems, but the logs do not quite understand what the problem is.

**Comment by GautamChibde** [comment]
@Semper-Viventem if you see Travis [configuration](https://travis-ci.org/FolioReader/FolioReader-Android/jobs/295286100/config) it is configured with the script "./gradlew checkstyle build" which you can run in your command line interface (on Linux) and looking into the file "_/FolioReader-Android/folioreader/build/reports/checkstyle/checkstyle.html_" will show you the errors, but its long list of issues. so I guess its fine to skip it for now :disappointed: (for this PR).

**Comment by ricardonservino** [comment]
Still getting conflict for attribute 'font'.
Is this still unresolved? Is there a workaround?

**Comment by Semper-Viventem** [comment]
@ricardonservino What version of the library are you using?

**Comment by GautamChibde** [comment]
@ricardonservino new version with this pull request isn't released yet will be fixed in next version.

**Comment by ricardonservino** [comment]
@Semper-Viventem I'm using:
compile 'com.folioreader:folioreader:0.3.2'

**Comment by Semper-Viventem** [comment]
@ricardonservino 
GautamChibde already answered the question. But I did a test build of the library for myself. You can use it before the official release


`com.github.Semper-Viventem.FolioReader-Android:webViewMarker:0.4.3
com.github.Semper-Viventem.FolioReader-Android:folioreader:0.4.3`

**Comment by ricardonservino** [comment]
@Semper-Viventem Awesome!
It has built just fine, I will test everything now.
Thanks for the fast replies @Semper-Viventem and @GautamChibde

**Pull request merged**
