### PR TITLE
Search implementation

### PR DESCRIPTION
**Pull request by salihaksit7**

### CODE REVIEW

**Comment by salihaksit7** [comment]
search implementation

**Comment by mahavir155** [comment]
@salihaksit7 thanks for PR.. We are bit busy with implementation of horizontal scrolling. We'll check your PR as soon as we have time..

**Comment by SonyGeorge** [comment]
@mahavir155 waiting eagerly for search to be implemented in folio reader, hope you will merge this ASAP ...

**Comment by mahavir155** [comment]
@salihaksit7 can you please resolve conflicts and update the PR?

**Comment by hrishikesh-kadam** [comment]
@salihaksit7 Hold on, I'll try to merge the PR in the proposed v0.4.1

**Comment by salihaksit7** [comment]
@hrishikesh-kadam  , Do I need to do anything? I am still holding on.

**Comment by hrishikesh-kadam** [comment]
@salihaksit7 We are working on your PR as it needs many improvements. We need UI to be more intuitive. 
Also the PR is only working for Vertical Scroll. From v0.4.0 Horizontal Scroll feature has been integrated and this would need extra work.

We will be working on [`codetoart:feature/search`](https://github.com/codetoart/FolioReader-Android/tree/feature/search) branch and once it is done it will be merged in `master`.

**Pull request merged**
