### PR TITLE
Master

### PR DESCRIPTION
**Pull request by compass00**
fixed bug: showed unrecognized code when href is image cover, then generated html.

### CODE REVIEW

**Comment by mahavir-jain** [comment]
@compass00 I cannot see your commits in this pull request? Did you pushed any commit related to issue https://github.com/FolioReader/FolioReader-Android/issues/35?

**Comment by compass00** [comment]
I commited in codetoart-master.

**Comment by mahavir-jain** [comment]
Yup, but it does not have any of your commits..

**Comment by compass00** [comment]
@mahavir-jain ，I do push commits... I don't know why you cannot see it...

**Comment by compass00** [comment]
oh, I cannot see my commits on Github too... but I can see commits on GitHub Desktop.When I click the push menu again, it shows: Authentication Failed,You may not have permission to access FolioReader-Android. Check Preferences to make sure you’re still logged in. I do logged in. May be I have not permission...
dd

**Comment by compass00** [comment]
I changed the file:
[changed.zip](https://github.com/FolioReader/FolioReader-Android/files/603251/changed.zip)

**Comment by compass00** [comment]
I would like to  try it again, Thanks...

**Comment by mahavir-jain** [comment]
@compass00 Sorry, I was just out of town.. You please send pull request from your forked repository.. Since you are not FolioReader member, you'll not be allowed to push directly in our repository..

**Pull request closed without merging**
